
services:
  phpmyadmin:
    networks:
      - astra_store
    image: phpmyadmin
    restart: always
    ports:
      - "3000:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
  database:
    networks:
      - astra_store
    image: 'mysql:8.0.35'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '3306:3306'
    volumes:
      - data_db:/var/lib/mysql:rw

networks:
  astra_store:
    driver: bridge

volumes:
  data_db: